version: '1.0'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - "/Users/qlin/Desktop/Fall2023/NoSQL/Mini Project:/usr/ds5760"
    networks:
      - app-network


  python-app:
      image: python:3.9-slim
      container_name: slim-python
      depends_on:
        - redis
      volumes:
        - "/Users/qlin/Desktop/Fall2023/NoSQL/Mini Project:/usr/ds5760"
      working_dir: /usr/ds5760/
      networks:
        - app-network
      command: tail -f /dev/null


networks:
  app-network:
    driver: bridge

